### ISSUE TITLE
Cannot compile on Ubuntu 12.04

### ISSUE THREAD

**Issue by alandmoore** [chjj/compton#48]
After pulling in the most recent changes from master, I cannot compile compton on Ubuntu 12.04, either 64 bit or 32 bit.  I have previously been able to compile with no problems on both systems, the last time I compiled successfully was 2012-09-04.

First time I try to compile I get an error about libconfig not being found; I installed libconfig8-dev and tried again.  This time I get these errors:

```
cc -Wall -std=c99    -c src/compton.c
src/compton.c: In function ‘condlst_add’:
src/compton.c:850:59: error: ‘PCRE_STUDY_JIT_COMPILE’ undeclared (first use in this function)
src/compton.c:850:59: note: each undeclared identifier is reported only once for each function it appears in
src/compton.c: In function ‘parse_config’:
src/compton.c:3072:5: warning: implicit declaration of function ‘config_set_include_dir’ [-Wimplicit-function-declaration]
src/compton.c:3089:3: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type [enabled by default]
/usr/include/libconfig.h:235:26: note: expected ‘long int *’ but argument is of type ‘int *’
src/compton.c:3098:3: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type [enabled by default]
/usr/include/libconfig.h:235:26: note: expected ‘long int *’ but argument is of type ‘int *’
src/compton.c:3102:3: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type [enabled by default]
/usr/include/libconfig.h:235:26: note: expected ‘long int *’ but argument is of type ‘int *’
src/compton.c:3104:3: warning: passing argument 3 of ‘config_lookup_int’ from incompatible pointer type [enabled by default]
/usr/include/libconfig.h:235:26: note: expected ‘long int *’ but argument is of type ‘int *’
make: *** [compton.o] Error 1
```

I tried make clean but it doesn't fix anything.  Not sure if I'm missing a library, I didn't see any new dependencies listed in README, and I do have libpcre-dev
